[workspace]
resolver = "2"
members = [
    "gtree_proc_macro",
    "gtree_macro",
    "gtree",
    "emg_core",
    "emg_layout",
    "emg_bind",
    "emg_refresh",
    "emg_state",
    "emg_animation",
    "emg_orders",
    "emg_debuggable",
    "emg_msg_macro",
    "emg_msg_impl",
    "emg_hasher",
    "tests",
]
# exclude = [""]
