[workspace]
resolver = "2"
members = [
    "gtree_proc_macro",
    "gtree_macro",
    "gtree",
    "emg_layout",
    "emg_bind",
    "emg_refresh",
    "emg_state",
    "emg_animation",
    "emg_orders"
]
exclude = [
    "tests",
]
