test-lib:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release --lib -- wasm_test::test2
bench:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release --lib -- wasm_test::benchmark
test-all:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release