test-lib:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release --lib -- wasm_test::test2
bench:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release --lib -- wasm_test::benchmark
bench_edge:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release --lib -- wasm_test::benchmark_edge_get
test-all:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release