[package]
name = "counter_new_resize"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false
resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
emg_bind = { path = "../../emg_bind" }
emg_refresh = { path = "../../emg_refresh" }
emg_state = { path = "../../emg_state" }
emg_layout = { path = "../../emg_layout" }
emg_animation = { path = "../../emg_animation" }
gtree = { path = "../../gtree" }
emg_core = { path = "../../emg_core" }

#
iced = { path = "../../../iced" }
seed_styles = { path = "../../../styles_hooks/seed_styles" }
anchors = { path = "../../../anchors" }


tracing = "0.1"

tracing-wasm = "0.2.1"
console_error_panic_hook = "0.1"

# im-rc = "15.0.0"
# serde = "1.0.130"
