[package]
name = "emg_animation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "^0.1" }
im="15.0.0"
iter_fixed = "0.2.0"
# emg_orders = { path = "../emg_orders"}

[dev-dependencies]
insta = {version = "1.7.1"}