[package]
name = "emg_layout"
version = "0.1.0"
authors = ["崔路明 <cuiluming@chaoway.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.24.1"
derive_more = "0.99"
seed_styles = { path = "../../styles_hooks/seed_styles" }
