[package]
name = "emg_graphics_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emg_native = { path = "../emg_native" }
#--------
raw-window-handle = "0.4"
thiserror = "1.0"
