[package]
name = "emg_bind"
version = "0.1.0"
authors = ["崔路明 <cuiluming@chaoway.net>"]
edition = "2018"
description = "element motion graph iced bind"
repository = "https://github.com"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["web", "iced"]
categories = ["web"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
iced = { path = "../../iced" }
emg = { path = "../../emg" }
functionate = { path = "../../functionate" }
overloadf = { path = "../../overloadf" }
illicit = "1.1.2"
log = "0.4"
lazy_static = "1.4.0"
dyn-clone = "1.0.4"
# downcast-rs = "1.2.0"

strum = "0.20.0"
strum_macros = "0.20"

match_any = "1.0.1"

emg_state = { path = "../emg_state" }
emg_refresh = { path = "../emg_refresh" }
emg_layout = { path = "../emg_layout" }
# for app
wasm-bindgen-futures = "0.4"


iced_style = { path = "../../iced/style" }
# from_variants = "0.5.0"
derive_more = "0.99.11"
delegate = "0.5.1"


tracing = { version = "^0.1" }


# [patch.crates-io]
# dodrio={path="../../dodrio"}

# [dependencies.bumpalo]
# version = "3.4.0"
# features = ["allocator_api"] 

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced_web = { version = "0.3", path = "../../iced/web" }
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"] }
console_log = { version = "0.2", features = ["color"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"


#for app
[dependencies.iced_futures]
version = "0.2"
path = "../../iced/futures"

# for app
[dependencies.web-sys]
version = "0.3.27"
features = [
    "console",
    "Document",
    "HtmlElement",
    "HtmlInputElement",
    "Event",
    "EventTarget",
    "InputEvent",
    "KeyboardEvent",
]
