[package]
name = "emg_bind"
version = "0.1.0"
authors = ["崔路明 <cuiluming@chaoway.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
anymap = "0.12.1"
iced = { path = "../../iced" }
emg  = { path = "../../emg"}
functionate ={ path="../../functionate"}
overloadf ={ path="../../overloadf"}
illicit="1.1.1"
log = "0.4"
console_log = { version = "0.2", features = ["color"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced_web = { version = "0.3", path = "../../iced/web" }
uuid = { version = "0.8", features = [ "v4","wasm-bindgen"] }


