[package]
name = "emg_bind"
version = "0.1.0"
authors = ["崔路明 <cuiluming@chaoway.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
anymap = "0.12.1"
iced = { path = "../../iced" }
emg  = { path = "../../emg"}
functionate ={ path="../../functionate"}
overloadf ={ path="../../overloadf"}
illicit="1.1.2"
log = "0.4"

# downcast-rs = "1.2.0"

strum = "0.20.0"
strum_macros = "0.20"

match_any = "1.0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced_web = { version = "0.3", path = "../../iced/web" }
uuid = { version = "0.8", features = [ "v4","wasm-bindgen"] }
console_log = { version = "0.2", features = ["color"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"