test-index:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release --lib -- dict_index_test
test-index-dict:
	wasm-pack test --chrome --chromedriver /opt/homebrew/bin/chromedriver --release --lib -- dict_index_test::dict_index_test_dict
